services:
  postgres:
    image: postgres:16
    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: myProject

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_app

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:admin@123@postgres:5432/myProject

volumes:
  postgres_data: